# ----------------------------------
# Project Euler - projecteuler.net
# ----------------------------------
# Developed by Felipe B Oriani
# 29 - Distinct powers
# How many distinct terms are in the sequence generated by a^b for 2 ? a ? 100 and 2 ? b ? 100?
# ----------------------------------

def f(baseMin, baseMax, expMin, expMax):
    s = set()
    for b in range(baseMin, baseMax+1):
        for e in range(expMin, expMax+1):
            s.add(pow(b, e))

    return len(s)

answer = f(2, 100, 2, 100)

print ('Answer: ', answer)

assert answer == 9183